# Generated by Django 3.1.1 on 2020-10-01 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20201001_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_admin',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='is_staff',
            new_name='staff',
        ),
    ]
