# Generated by Django 3.1.1 on 2020-10-01 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20201001_0632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='admin',
            new_name='is_admin',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
